website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, jsonify
from flask_csp.csp import csp_header

from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
import qrcode
from . import db
import secrets
auth = Blueprint("auth", __name__)
salt = str(secrets.token_urlsafe(10))
pepper = "M"
from flask import abort
from io import BytesIO
import pyqrcode
from flask import session

@auth.route("/login", methods=['GET', 'POST'])
@csp_header({'default-src':"'none'",'script-src':"'self'"})
def login():

    if request.method == 'POST':
        username = request.form.get("username")
        password = request.form.get("password")
        otp_verification = request.form.get("remember")

        #TODO sprawdznie wpisywanych danych
        if '"' in username or '"' in password:
            return "Error, pls don't try to hack our page :)"
        user = User.query.filter_by(username=username).first()

        if user:
            if otp_verification == "on" :
                if user.otp:
                    return redirect(url_for('auth.login'))
                    print("Nie logujesz się pierwszy raz")
                if check_password_hash(user.password, f'{user.salt}{password}{pepper}'):
                    login_user(user, remember=True)
                    return redirect(url_for('auth.two_factor_setup'))
                    #return redirect(url_for('views.home'))
                else:
                    print("zle haslo")
                    flash('Password is incorrect.', category='error')
            else:
                otp = request.form.get("otp")
                if otp is not None:
                    otp = int(otp)

                if  check_password_hash(user.password, f'{user.salt}{password}{pepper}') and  user.verify_totp(otp):
                    login_user(user, remember=True)
                    if user.role == "D":
                        return redirect(url_for('views.doctor'))
                    elif user.role == "P":
                        return redirect(url_for('views.patient'))
                else:
                    print('Incorrect password or token.')

        else:
            flash('Username does not exist.', category='error')
            print('nie ma tego username')

    return render_template("index.html", user=current_user)



@auth.route("/logout")
@csp_header({'default-src':"'none'",'script-src':"'self'"})
def logout():
    logout_user()
    return redirect(url_for("views.home"))

@auth.route('/twofactor')
@csp_header({'default-src':"'none'",'script-src':"'self'"})
@login_required
def two_factor_setup():
    # since this page contains the sensitive qrcode, make sure the browser does not cache it
    return render_template('two-factor-setup.html'), 200, {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'}

@auth.route('/qr')
@csp_header({'default-src':"'none'",'script-src':"'self'"})
@login_required
def qr():

    user = current_user
    print(user)
    # render qrcode for FreeTOTP
    url = qrcode.make(user.get_totp_uri())
    qrcode.make(user.get_totp_uri()).save("website/code.jpg")
    # stream = BytesIO()
    # url.svg(stream, scale=5)
    #return stream.getvalue(), 200
    return jsonify({"sukces"}), 200


@auth.route('/qr_code')
@csp_header({'default-src':"'none'",'script-src':"'self'"})
def qr_code():

    user = current_user
    url = pyqrcode.create(user.get_totp_uri())
    stream = BytesIO()
    url.svg(stream, scale=5)
    return stream.getvalue(), 200, {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'}

@auth.route("/check" ,methods=['GET', 'POST'])
@csp_header({'default-src':"'none'",'script-src':"'self'"})
def check_otp():
    if request.method == 'POST':
        otp = request.form.get("otp")

website/templates/doctor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/styles.css">
    <title> Health Record Book </title>
</head>
<body>

  <header>
        <div class="title">
            <h1>Health Record Book</h1>
        </div>
        <div class="buttons">
  <a href="/logout"><button onclick="logout()">Logout</button></a>
        </div>
    </header>
    <section class="main-content">
                <div class="main-title">
                           <h2>Patients Health Records</h2>

                </div>
        {%    for patient in response %}
        <div class="all-patients-form">
            <!-- Your login form can be added here -->
 <form action="/doctor/{{patient['id']}}">
            <div class="patient-info-box">
                <div class="patient-info">

                    <p><strong> Name:  </strong> {{patient['name_surname']}}
                    <strong>Date of Birth:  </strong> {{patient['birth_date']}}
                    <strong>Diseases:  </strong> {{patient['diseases']}}
                    <strong>Vaccinated:  </strong> {{patient['vaccinations']}} </p>
                        <input type="submit" value="Edit">

                </div>
            </div>
          </form>
        </div>
        {% endfor %}

    </section>

    <footer>
        <p>&copy; 2024 Engineering Thesis.</p>
    </footer>

</body>
</html>

website/templates/doctor_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/styles.css">
    <title> Health Record Book </title>
</head>
<body>

  <header>
        <div class="title">
            <h1>Health Record Book</h1>
        </div>
        <div class="buttons">
            <a href="/doctor"><button >All Health Books</button></a>
            <a href="/logout"><button onclick="logout()">Logout</button></a>
        </div>
    </header>
    <section class="main-content">
        <div class="login-form">
            <!-- Your login form can be added here -->
            <h2>Patient Health Record</h2>

            <div class="patient-info-box">
                <div class="patient-info">
                    <p><strong>Name: </strong> {{response[0]['name_surname']}} </p>
                     <p><strong>Date of Birth: </strong> {{response[0]['birth_date']}}</p>
                    <p><strong>Diseases: </strong> {{response[0]['diseases']}}</p>
                    <form method="post">
                        <label>Add disease:</label>
                <input autocomplete="off" type="text"  name="disease">
                        <button type="submit">Add</button>
                    </form>
                    <p><strong> Vaccinations: </strong>{{response[0]['vaccinations']}}</p>
                    <form method="post">
                <label>Add vacination:</label>
                <input type="text" autocomplete="off" name="vaccination">
                        <button type="submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <footer>
        <p>&copy; 2024 Engineering Thesis.</p>
    </footer>

</body>
</html>

website/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/style.css">
    <title> Health Record Book </title>

</head>
<body>

    <header>
        <h1>Health Record Book</h1>
        <!-- You can add a navigation bar or other header elements here -->
    </header>

    <section class="main-content">
        <div class="content">
            <h2>Welcome to your secured health record books</h2>
            <p> Rest assured knowing your data is secured. Our record books are built with robust </p>
            <p> security measures, prioritizing confidentiality and protection against unauthorized access. </p>
        </div>

        <div class="login-form">
            <h2>Login</h2>
            <!-- Your login form can be added here -->
            <form action="/login" method="post">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" value="{{ csrf_token() }}" required>

                <label for="password">Password:</label>
                <input type="password" id="password" name="password"  value="{{ csrf_token() }}"  required>
                <div class="first-login">
                    <input type="checkbox" id="remember" name="remember">
                    <label for="remember">First login</label>
                </div>
                <label >OTP:</label>
                <input type="text" name="otp">
                <input type="submit" value="Login">
            </form>
        </div>
    </section>

    <footer>
        <p>&copy; 2024 Engineering Thesis.</p>
    </footer>

</body>
</html>

website/templates/patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/styles.css">
    <title> Health Record Book </title>
</head>
<body>

  <header>
        <div class="title">
            <h1>Health Record Book</h1>
        </div>
        <div class="buttons">
              <a href="/logout"><button onclick="logout()">Logout</button></a>
        </div>
    </header>
    <section class="main-content">
        <div class="login-form">
            <!-- Your login form can be added here -->
            <h2>Patient Health Record</h2>
            <div class="patient-info-box">
                <div class="patient-info">
                    <p><strong>Name: </strong> {{response[0]['name_surname']}} </p>
                    <p><strong>Date of Birth: </strong> {{response[0]['birth_date']}}</p>
                    <p><strong>Diseases: </strong> {{response[0]['diseases']}}</p>
                    <p><strong>Vaccinations: </strong>{{response[0]['vaccinations']}}</p>
                </div>
            </div>
        </div>
    </section>

    <footer>
        <p>&copy; 2024 Engineering Thesis.</p>
    </footer>

</body>
</html>

website/templates/two-factor-setup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="static/styles.css">
    <title> Health Record Book </title>
</head>
<body>

  <header>
        <div class="title">
            <h1>Health Record Book</h1>
        </div>
    </header>
  <center>
    <section class="main-content">

         <h1>Two Factor Authentication Setup</h1>
    <p>You are almost done! Please start Authenticator on your smartphone and scan the following QR Code with it:</p>
    <p><img id="qr-code" src="{{ url_for('auth.qr_code') }}" alt="QR Code" />
        </p>

    <p>I'm done, take me to the  <a href="{{ url_for('views.home') }}">Home</a> page!</p>
    </section>
  </center>
    <footer>
        <p>&copy; 2024 Engineering Thesis.</p>
    </footer>

</body>
</html>